[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = ""  # Отключен healthcheck, так как Ollama не предоставляет /api/health
healthcheckTimeout = 600  # Увеличено до 600 секунд (на случай, если healthcheck будет включен)
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[services]]
name = "ollama"
internal_port = 11434
protocol = "tcp"

[[volumes]]
name = "ollama_data"
mountPath = "/root/.ollama"
persistent = true

[service.resources]
memory_mb = 12288  # Увеличено до 12 ГБ
cpu_units = 2000

[service.environment]
OLLAMA_HOST = "0.0.0.0"
OLLAMA_MODELS_PATH = "/root/.ollama/models"
